version: "3.8"

services:
  db:
    image: postgres:15
    container_name: postgres-db
    restart: always
    env_file: .env
    ports:
      - "${POSTGRES_DB_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    build: .
    container_name: nextjs-app
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file: .env
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    # development:
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    # command: sh -c "npx prisma migrate deploy && npx prisma db seed && npm start"

volumes:
  pgdata:
